import { readdir, readFile } from "node:fs/promises";

import { finding, isMissing, redact, type DoctorFinding } from "src/core/doctor/findings.js";
import { ownershipState, type ManagedEntry, type ManagedManifest } from "src/core/managed/project-files.js";
import { resolveSafeProjectPath } from "src/utils/paths.js";

/** Project-local platform surfaces written by Harnix before platform setup became user-global. */
const LEGACY_SURFACE_CANDIDATES = [
  ".kiro/hooks/harnix-context.kiro.hook",
  ".kiro/hooks/harnix-context.json",
  ".kiro/steering/harnix.md",
  ".gemini/skills/harnix-implement/SKILL.md",
  ".agents/skills/harnix-implement/SKILL.md",
  ".agents/hooks.json",
  ".agents/plugins/harnix/hooks.json",
  ".codex/hooks.json",
  ".codex/config.toml",
  "AGENTS.md",
  "GEMINI.md",
] as const;

const LEGACY_SKILL_ROOTS = [".kiro/skills", ".gemini/skills", ".agents/skills"] as const;

const LEGACY_HOOK_PATHS = new Set([
  ".kiro/hooks/harnix-context.kiro.hook",
  ".kiro/hooks/harnix-context.json",
  ".codex/hooks.json",
  ".agents/hooks.json",
  ".agents/plugins/harnix/hooks.json",
]);

export async function inspectLegacyEntry(root: string, entry: ManagedEntry, findings: DoctorFinding[]): Promise<void> {
  try {
    const state = await ownershipState(root, entry, entry);
    if (state === "unchanged") {
      findings.push(
        finding(
          "legacy-project-surface",
          "info",
          entry.path,
          "A manifest-proven project-local platform surface remains; use uninstall --legacy-project-surfaces to remove it explicitly.",
          false,
        ),
      );
      if (LEGACY_HOOK_PATHS.has(entry.path)) {
        findings.push(
          finding(
            "legacy-project-duplicate-hook",
            "warning",
            entry.path,
            "A manifest-proven project-local Harnix hook may run alongside the user-global integration; use uninstall --legacy-project-surfaces to remove it explicitly.",
            false,
          ),
        );
      }
    } else if (state === "modified")
      findings.push(
        finding(
          "legacy-project-surface-modified",
          "warning",
          entry.path,
          "A legacy project-local platform surface was modified and will be preserved.",
          false,
        ),
      );
    else
      findings.push(
        finding(
          "legacy-project-surface-missing",
          "warning",
          entry.path,
          "A manifest-proven legacy project-local platform surface is missing.",
          false,
        ),
      );
  } catch (error) {
    findings.push(finding("legacy-project-surface-unsafe", "error", entry.path, redact(error, root), false));
  }
}

export async function inspectUntrackedLegacySurfaces(
  root: string,
  manifest: ManagedManifest,
  findings: DoctorFinding[],
): Promise<void> {
  const candidates = new Set<string>([
    ...LEGACY_SURFACE_CANDIDATES,
    ...(await findLegacySkillCandidates(root, findings)),
  ]);
  for (const path of [...candidates].sort()) {
    if (manifest.entries.some((entry) => entry.scope !== "project" && entry.path === path)) continue;
    const text = await readOptionalSafe(root, path, findings);
    if (text.length === 0 || !looksLikeHarnix(path, text)) continue;
    const duplicateHook = LEGACY_HOOK_PATHS.has(path) && /harnix\s+internal\s+context/iu.test(text);
    findings.push(
      duplicateHook
        ? finding(
            "legacy-project-duplicate-hook",
            "warning",
            path,
            "An untracked project-local Harnix hook may run alongside the user-global integration; it will not be removed automatically.",
            false,
          )
        : finding(
            "legacy-project-surface-untracked",
            "warning",
            path,
            "An untracked legacy Harnix platform surface may duplicate the user-global integration; it will not be removed automatically.",
            false,
          ),
    );
  }
}

function looksLikeHarnix(path: string, text: string): boolean {
  if (path.endsWith("hooks.json")) return /harnix\s+internal\s+context/iu.test(text);
  if (path === "GEMINI.md") return /<!-- harnix:(?:begin|end) -->/u.test(text);
  if (path === "AGENTS.md") return hasHistoricalProjectLocalAgentsBlock(text);
  if (path === ".codex/config.toml") return /^\s*\[harnix\]/imu.test(text);
  return /harnix/iu.test(text);
}

function hasHistoricalProjectLocalAgentsBlock(text: string): boolean {
  const begin = text.indexOf("<!-- harnix:begin -->");
  const end = text.indexOf("<!-- harnix:end -->", begin);
  if (begin < 0 || end < begin) return false;
  return text.slice(begin, end).includes("Project-local skills are generated by harnix setup");
}

async function findLegacySkillCandidates(root: string, findings: DoctorFinding[]): Promise<string[]> {
  const candidates: string[] = [];
  for (const skillRoot of LEGACY_SKILL_ROOTS) {
    try {
      const directory = await resolveSafeProjectPath(root, skillRoot);
      const entries = await readdir(directory, { withFileTypes: true });
      for (const entry of entries) {
        if (entry.name.startsWith("harnix-")) candidates.push(`${skillRoot}/${entry.name}/SKILL.md`);
      }
    } catch (error: unknown) {
      if (!isMissing(error))
        findings.push(finding("legacy-surface-inspection-failed", "warning", skillRoot, redact(error, root), false));
    }
  }
  return candidates;
}

/** Reads a project file, reporting an unsafe path as a finding; a missing file is an empty string. */
export async function readOptionalSafe(root: string, path: string, findings: DoctorFinding[]): Promise<string> {
  try {
    return await readFile(await resolveSafeProjectPath(root, path), "utf8");
  } catch (error: unknown) {
    if (isMissing(error)) return "";
    findings.push(finding("unsafe-path", "error", path, redact(error, root), false));
    return "";
  }
}
