import { describe, expect, it } from "vitest";

import * as workflow from "src/core/workflow/index.js";

describe("workflow index", () => {
  it("exposes exactly the public workflow surface used by commands and hooks", () => {
    expect(Object.keys(workflow).sort()).toEqual([
      "addCriterionWorkflow",
      "addDecisionWorkflow",
      "addRiskWorkflow",
      "appendEvidenceFlagsWorkflow",
      "appendEvidenceWorkflow",
      "batchWorkflow",
      "briefPreflight",
      "briefTask",
      "canCompleteTask",
      "cancelWorkflow",
      "cancelWorkflowTask",
      "contextSelectionInput",
      "continueWorkflowTask",
      "evidenceSupportsScope",
      "finishWorkflow",
      "finishWorkflowReport",
      "finishWorkflowTask",
      "implementationStrategy",
      "initTaskWorkflow",
      "inspectWorkflow",
      "isWithinRequestedScope",
      "markCriteriaMetWorkflow",
      "migrateToV3Workflow",
      "nextWorkflowStatus",
      "preflightWorkflow",
      "recordLearningWorkflow",
      "recordWorkflowLearning",
      "replaceCheckWorkflow",
      "routeWorkflow",
      "runCheckWorkflow",
      "runChecksWorkflow",
      "saveWorkflow",
      "setBaselineWorkflow",
      "setCheckWorkflow",
      "setCriterionWorkflow",
      "setEpicOrderWorkflow",
      "setPathsWorkflow",
      "shouldReassessArchitecture",
      "shouldResearch",
      "snapshotWorkflow",
      "taskContextDrift",
      "transitionWorkflow",
      "validateFullReadyArtifact",
      "validateWorkflowBatchEnvelope",
      "verificationRetryDisposition",
      "verificationStages",
      "withTargetTask",
      "workflowEnvelopeSchema",
    ]);
  });
});
