/**
 * The declarative platform records. Kept beside `registry.ts` so the registry module stays the
 * types-plus-API surface while the platform data (one record per supported coding agent) lives here.
 * Adding a platform means adding one record and its facts, never a new code branch.
 */

import {
  ANTIGRAVITY_FACTS,
  CLAUDE_FACTS,
  CODEX_FACTS,
  CURSOR_FACTS,
  KIRO_FACTS,
  OPENCODE_FACTS,
} from "src/core/platform/facts.js";
import type { PlatformRecord } from "src/core/platform/registry.js";

export const PLATFORM_RECORDS = [
  {
    id: "kiro",
    label: "Kiro",
    flag: "kiro",
    executable: "kiro-cli",
    roots: [{ key: "config", relativePath: ".kiro", logicalPath: "~/.kiro", envOverride: null }],
    skillDirectories: ["config:skills"],
    instructionFile: "steering/harnix.md",
    contextHook: { event: "UserPromptSubmit", command: "harnix context --platform kiro" },
    contextOutput: "plain",
    contextFirstInvocationOnly: false,
    contextRenderCap: null,
    targets: [
      {
        rootKey: "config",
        globalPlatform: "kiro",
        manifestPath: "harnix/managed.json",
        lockPath: "harnix/managed.lock",
        preserveUnownedRoot: false,
        planKey: "kiro",
      },
    ],
    healthyReadiness: "installed",
    setupNotice: null,
    ambiguousRootEnv: "KIRO_HOME",
    shadowingFiles: [],
    facts: KIRO_FACTS,
  },
  {
    id: "antigravity",
    label: "Antigravity",
    flag: "antigravity",
    executable: "agy",
    roots: [
      {
        key: "desktop",
        relativePath: ".gemini/config/plugins/harnix",
        logicalPath: "~/.gemini/config/plugins/harnix",
        envOverride: null,
      },
      {
        key: "cli",
        relativePath: ".gemini/antigravity-cli/plugins/harnix",
        logicalPath: "~/.gemini/antigravity-cli/plugins/harnix",
        envOverride: null,
      },
    ],
    skillDirectories: ["desktop:skills", "cli:skills"],
    instructionFile: "rules/AGENTS.md",
    contextHook: { event: "PreInvocation", command: "harnix context --platform antigravity" },
    contextOutput: "antigravity-inject-steps",
    contextFirstInvocationOnly: true,
    contextRenderCap: null,
    targets: [
      {
        rootKey: "desktop",
        globalPlatform: "antigravity-desktop",
        manifestPath: ".managed.json",
        lockPath: ".managed.lock",
        preserveUnownedRoot: true,
        planKey: "antigravity-plugin",
      },
      {
        rootKey: "cli",
        globalPlatform: "antigravity-cli",
        manifestPath: ".managed.json",
        lockPath: ".managed.lock",
        preserveUnownedRoot: true,
        planKey: "antigravity-plugin",
      },
    ],
    healthyReadiness: "precedence-unknown",
    setupNotice:
      "Antigravity plugin-versus-workspace hook precedence is not verified; inspect the active tool session before relying on injection.",
    ambiguousRootEnv: null,
    shadowingFiles: [],
    facts: ANTIGRAVITY_FACTS,
  },
  {
    id: "codex",
    label: "Codex",
    flag: "codex",
    executable: "codex",
    roots: [
      { key: "config", relativePath: ".codex", logicalPath: "~/.codex", envOverride: "CODEX_HOME" },
      { key: "skills", relativePath: ".agents", logicalPath: "~/.agents", envOverride: null },
    ],
    skillDirectories: ["skills:skills"],
    instructionFile: "AGENTS.md",
    contextHook: { event: "UserPromptSubmit", command: "harnix context --platform codex" },
    contextOutput: "codex-additional-context",
    contextFirstInvocationOnly: false,
    contextRenderCap: 2_500,
    targets: [
      {
        rootKey: "config",
        globalPlatform: "codex",
        manifestPath: "harnix/managed.json",
        lockPath: "harnix/managed.lock",
        preserveUnownedRoot: false,
        planKey: "codex-config",
      },
      {
        rootKey: "skills",
        globalPlatform: "codex",
        manifestPath: "harnix/managed.json",
        lockPath: "harnix/managed.lock",
        preserveUnownedRoot: false,
        planKey: "codex-skills",
      },
    ],
    healthyReadiness: "installed-pending-trust",
    setupNotice: "Review and trust the exact Harnix hook from Codex /hooks before it can run.",
    ambiguousRootEnv: null,
    shadowingFiles: [
      { rootKey: "config", path: "AGENTS.override.md", code: "codex-agents-override", subject: "AGENTS override" },
    ],
    facts: CODEX_FACTS,
  },
  {
    id: "claude",
    label: "Claude Code",
    flag: "claude",
    executable: "claude",
    roots: [{ key: "config", relativePath: ".claude", logicalPath: "~/.claude", envOverride: "CLAUDE_CONFIG_DIR" }],
    skillDirectories: ["config:skills"],
    instructionFile: "CLAUDE.md",
    contextHook: { event: "UserPromptSubmit", command: "harnix context --platform claude" },
    contextOutput: "plain",
    contextFirstInvocationOnly: false,
    contextRenderCap: null,
    targets: [
      {
        rootKey: "config",
        globalPlatform: "claude",
        manifestPath: "harnix/managed.json",
        lockPath: "harnix/managed.lock",
        preserveUnownedRoot: false,
        planKey: "claude",
      },
    ],
    healthyReadiness: "installed",
    setupNotice: null,
    ambiguousRootEnv: null,
    shadowingFiles: [],
    facts: CLAUDE_FACTS,
  },
  {
    id: "opencode",
    label: "OpenCode",
    flag: "opencode",
    executable: "opencode",
    roots: [{ key: "config", relativePath: ".config/opencode", logicalPath: "~/.config/opencode", envOverride: null }],
    skillDirectories: ["config:skills"],
    instructionFile: "AGENTS.md",
    contextHook: null,
    contextOutput: "plain",
    contextFirstInvocationOnly: false,
    contextRenderCap: null,
    targets: [
      {
        rootKey: "config",
        globalPlatform: "opencode",
        manifestPath: "harnix/managed.json",
        lockPath: "harnix/managed.lock",
        preserveUnownedRoot: false,
        planKey: "opencode",
      },
    ],
    healthyReadiness: "installed",
    setupNotice:
      "OpenCode's ~/.config/opencode/AGENTS.md takes precedence over the ~/.claude/CLAUDE.md fallback, so Harnix's marked block there replaces that prompt fallback; no shell hook exists, so OpenCode runs hookless.",
    ambiguousRootEnv: null,
    shadowingFiles: [],
    facts: OPENCODE_FACTS,
  },
  {
    id: "cursor",
    label: "Cursor",
    flag: "cursor",
    executable: "cursor-agent",
    roots: [{ key: "config", relativePath: ".cursor", logicalPath: "~/.cursor", envOverride: null }],
    skillDirectories: ["config:skills"],
    instructionFile: null,
    contextHook: null,
    contextOutput: "plain",
    contextFirstInvocationOnly: false,
    contextRenderCap: null,
    targets: [
      {
        rootKey: "config",
        globalPlatform: "cursor",
        manifestPath: "harnix/managed.json",
        lockPath: "harnix/managed.lock",
        preserveUnownedRoot: false,
        planKey: "cursor",
      },
    ],
    healthyReadiness: "installed",
    setupNotice:
      "Cursor has no global instruction file (User Rules are UI-only) and its sessionStart hook injection is unverified, so Harnix installs only skills and runs hookless.",
    ambiguousRootEnv: null,
    shadowingFiles: [],
    facts: CURSOR_FACTS,
  },
] as const satisfies readonly PlatformRecord[];
