export const harnixAgentsBlock = `<!-- harnix:begin -->
## Harnix workflow

This repository uses Harnix as its project-local coding-agent harness. The Harnix CLI manages project lifecycle surfaces; installed Harnix skills and .harnix/workflow.md drive coding tasks.

Use harnix --help or harnix <command> --help for exact CLI syntax; do not guess flags. Public commands are init, setup, update, upgrade, uninstall, mem, and doctor. They manage the harness and diagnostics, not coding-task stage transitions.

Project-local skills are generated by harnix setup --kiro, harnix setup --antigravity, or harnix setup --codex. Run setup only for the platform requested or explicitly authorized; if its skills are absent, report that setup is required instead of simulating them.

Before work:

1. Read .harnix/workflow.md and .harnix/config.yaml, then load only the context relevant to the request.
2. If .harnix/tasks/.active identifies an unfinished task, use harnix-continue and resume its persisted status, checkpoint, and evidence.
3. Otherwise classify the request as Bypass, Lite, or Full using .harnix/workflow.md. Read-only answers may bypass task creation; implementation work follows the selected workflow.

Use the skills in this order when their stage applies:

- harnix-brainstorm: establish scope, acceptance criteria, validation, and the ready gate.
- harnix-implement: implement a ready task; use RED-GREEN-REFACTOR for behavior changes unless a documented exception applies.
- harnix-check: run compliance checks before quality and security checks, using fresh evidence.
- harnix-finish-work: complete and archive only after every acceptance criterion and required check passes.
- harnix-research and harnix-debug: use only for material unknowns or failures; harnix-continue restores persisted work.

The persisted lifecycle is planning -> ready -> in_progress -> verifying -> completed. A blocked task resumes only to its recorded status. Do not skip gates or treat stale, partial, or inferred output as verification.

Operating rules:

- Preserve user-owned files, tasks, specs, research, journals, credentials, and unrelated configuration.
- Keep generated paths repository-relative and never expose secrets, prompts, or machine-specific absolute paths in output.
- Run harnix doctor --json when managed files, platform setup, or project state may have drifted.
- Require explicit user authorization for destructive, networked, installation, upgrade, purge, or externally visible actions.
- Never commit, branch, create a worktree, merge, push, publish, or create a pull request automatically.
- If the CLI, a required skill, or persisted state is unavailable or invalid, report the problem instead of inventing Harnix state or schemas.
<!-- harnix:end -->`;

export const agentsTemplate = `# Project agent instructions

${harnixAgentsBlock}
`;
